---
title: "Adding rcpptimer to a Package"
author: Jonathan Berrisch
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    number_sections: no
    toc: no
vignette: >
  %\VignetteIndexEntry{Adding rcpptimer to a Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Adding rcpptimer to your Package

Using rcpptimer in your package is simple. Just link to it in your `DESCRIPTION` file:

```r
LinkingTo: rcpptimer (>= 1.2.0)
```

and add the header into your .cpp file `#include <rcpptimer.h>`. Now, you can create and use an instance of the `Rcpp::Timer` class. Consider this `fibonacci_omp` function:

```c++
#include <rcpptimer.h>

long int fib(long int n)
{
  return ((n <= 1) ? n : fib(n - 1) + fib(n - 2));
}

//[[Rcpp::export]]
std::vector<long int> fibonacci_omp(std::vector<long int> n)
{
  Rcpp::Timer timer;
 // This scoped timer measures the total execution time of 'fibonacci'
  Rcpp::Timer::ScopedTimer scpdtmr(timer, "fib_body");
  std::vector<long int> results = n;
  #pragma omp parallel for
  for (unsigned int i = 0; i < n.size(); ++i)
  {
    timer.tic("fib_" + std::to_string(n[i]));
    results[i] = fib(n[i]);
    timer.toc("fib_" + std::to_string(n[i]));
  }
  return (results);
}
```
This function is available in rcpptimer you can try it yourself, e.g.  `rcpptimer::fibonacci(n = rep(20:25, 10))`. After that you can observe the timings by executing `print(times)`.

As you see, it writes the timings to the global environment as data.frame called `times`. Read the following section to learn why this is not what you want in a package. 

## Autoreturn

When using rcpptimer in your package, you should consider disabling the timer's autoreturn feature. Users of your package may not be aware of this functionality. They may already have an object named `times` in their global environment, or may have very strict expectations about what objects they want to write into their environment.
Instead, you should include the timings in your data structures or parameterize the name of the returned object, the autoreturn feature itself, or both.

See `vignette("autoreturn")` vignette to read about this in detail.